version: "3.9"
services:
  mongo-primary:
    image: mongo:latest
    container_name: mongo-primary
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: admin
    ports:
      - "27017:27017"
    volumes:
      - mongo-primary-data:/data/db
      - ./mongo/mongodb-keyfile:/etc/mongo/keyfile
    networks:
      - mongo-replica
    command: ["--replSet", "rs0", "--keyFile", "/etc/mongo/keyfile"]

  mongo-secondary:
    image: mongo:latest
    container_name: mongo-secondary
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27018:27017"
    volumes:
      - mongo-secondary-data:/data/db
      - ./mongo/mongodb-keyfile:/etc/mongo/keyfile
    networks:
      - mongo-replica
    command: ["--replSet", "rs0", "--keyFile", "/etc/mongo/keyfile"]

  mongo-arbiter:
    image: mongo:latest
    container_name: mongo-arbiter
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27019:27017"
    networks:
      - mongo-replica
    volumes:
      - ./mongo/mongodb-keyfile:/etc/mongo/keyfile
    command: ["--replSet", "rs0", "--keyFile", "/etc/mongo/keyfile"]

volumes:
  mongo-primary-data:
  mongo-secondary-data:

networks:
  mongo-replica:
    driver: bridge
